USE q_a_db;
INSERT INTO `users` (login, password, email, full_name, `role`)
VALUES ("user 1", "$2b$05$No6FynbDPY46LSWp.0khcOURv2d8JH2e9o8pKA3bCv1fKv5PyWfFm", "u1@mail.com", "user u1", "user"),
       ("user 2", "$2b$05$No6FynbDPY46LSWp.0khcOURv2d8JH2e9o8pKA3bCv1fKv5PyWfFm", "u2@mail.com", "user u2", "user"),
       ("user 3", "$2b$05$No6FynbDPY46LSWp.0khcOURv2d8JH2e9o8pKA3bCv1fKv5PyWfFm", "u3@mail.com", "user u3", "user"),
       ("user 4", "$2b$05$No6FynbDPY46LSWp.0khcOURv2d8JH2e9o8pKA3bCv1fKv5PyWfFm", "u4@mail.com", "user u4", "user"),
       ("user 5", "$2b$05$No6FynbDPY46LSWp.0khcOURv2d8JH2e9o8pKA3bCv1fKv5PyWfFm", "u5@mail.com", "user u5", "user");

INSERT INTO `category` (title, `description`)
VALUES ("HMFS main", "Half Marathon Full Stack main questions"),
       ("HMFS S 01", "Sprint 01 Half Marathon Full Stack"),
       ("HMFS S 02", "Sprint 02 Half Marathon Full Stack"),
       ("HMFS S 03", "Sprint 03 Half Marathon Full Stack"),
       ("HMFS S 04", "Sprint 04 Half Marathon Full Stack"),
       ("HMFS S 05", "Sprint 05 Half Marathon Full Stack"),
       ("HTML", "All about HTML"),
       ("CSS", "All about CSS"),
       ("JS", "All about JS"),
       ("Green LMS", "All about https://green-lms.app"),
       ("cat1", "discr1"),
       ("cat2", "discr2"),
       ("cat3", "discr3"),
       ("cat4", "discr4"),
       ("cat5", "discr5");


INSERT INTO `posts` (author, title, content)
VALUES (1, " top-level statements", "Добрий день! Є питання щодо того, як обсерве що
                                    треба конкретний namespace i class, наприклад з т00 по т03 завдання? Чи краще використовувати block-scoped
                                    namespaces?"),


       (1, "t1", "cont1"),
       (1, "t2", "cont2"),
       (2, "t35", "cont3"),
       (2, "t3", "cont1"),
       (3, "t36", "cont3"),
       (3, "t31", "cont35"),
       (4, "t5", "cont6"),
       (4, "t6", "cont65"),
       (5, "t22", "cont22"),
       (1, "t1", "cont22"),
       (1, "t2", "cont22");


INSERT INTO `post_category` (post_id, category_id)
VALUES (1, 1),
       (1, 2),
       (2, 2),
       (3, 1),
       (3, 3),
       (3, 4),
       (4, 5),
       (5, 1),
       (5, 2),
       (5, 3),
       (6, 4),
       (7, 2),
       (7, 5),
       (8, 3),
       (9, 1),
       (9, 4),
       (10, 2),
       (10, 3),
       (10, 5),
       (11, 1);



INSERT INTO `comments` (author, post_id, content)
VALUES (1, 1, 'something'),
       (1, 1, 'Nice post!'),
       (2, 2, 'I agree with you'),
       (3, 3, 'Interesting idea'),
       (4, 4, 'Good explanation'),
       (5, 5, 'Thanks for sharing'),
       (6, 6, 'Very helpful'),
       (1, 7, 'I learned something new'),
       (2, 8, 'Cool example'),
       (3, 9, 'That makes sense'),
       (4, 10, 'Clear and simple'),
       (5, 11, 'Love this'),
       (6, 1, 'Can you explain more?'),
       (1, 2, 'I had the same thought'),
       (2, 3, 'Sounds good'),
       (3, 4, 'Helpful tips'),
       (4, 5, 'I disagree a little'),
       (5, 6, 'Brilliant!'),
       (6, 7, 'Nice question'),
       (1, 8, 'Short and clear'),
       (2, 9, 'Thanks a lot'),
       (3, 10, 'Keep it up'),
       (4, 11, 'Simple words'),
       (5, 1, 'Nice and easy'),
       (6, 2, 'Clear example'),
       (1, 3, 'Very true'),
       (2, 4, 'Good advice'),
       (3, 5, 'I appreciate this'),
       (4, 6, 'That helps me'),
       (5, 7, 'Good point'),
       (6, 8, 'Perfect timing'),
       (1, 9, 'I like it'),
       (2, 10, 'Exactly what I needed'),
       (3, 11, 'Good answer'),
       (4, 1, 'Great idea'),
       (5, 2, 'Well said'),
       (6, 3, 'This is useful'),
       (1, 4, 'Smart solution'),
       (2, 5, 'Clear view'),
       (3, 6, 'That’s right'),
       (4, 7, 'Helpful note'),
       (5, 8, 'I understand now'),
       (6, 9, 'Sounds logical'),
       (1, 10, 'Great help'),
       (2, 11, 'Nice logic'),
       (3, 1, 'Cool thought'),
       (4, 2, 'Very nice'),
       (5, 3, 'Works fine'),
       (6, 4, 'Good one');


INSERT INTO `likes` (author, post_id, comment_id, `type`)
VALUES (1, 2, NULL, FALSE),
       (1, 3, NULL, TRUE),
       (1, 4, NULL, FALSE),
       (1, 5, NULL, TRUE),
       (1, 7, NULL, TRUE),
       (1, 8, NULL, FALSE),
       (1, 9, NULL, TRUE),
       (1, 10, NULL, FALSE),
       (1, 11, NULL, TRUE),
       (2, 1, NULL, FALSE),
       (2, 2, NULL, TRUE),
       (2, 3, NULL, FALSE),
       (2, 4, NULL, TRUE),
       (2, 5, NULL, FALSE),
       (2, 7, NULL, FALSE),
       (2, 8, NULL, TRUE),
       (2, 9, NULL, FALSE),
       (2, 10, NULL, TRUE),
       (2, 11, NULL, FALSE),
       (3, 1, NULL, TRUE),
       (3, 2, NULL, FALSE),
       (3, 3, NULL, TRUE),
       (3, 4, NULL, FALSE),
       (3, 5, NULL, TRUE),
       (3, 6, NULL, FALSE),
       (3, 7, NULL, TRUE),
       (3, 8, NULL, FALSE),
       (3, 9, NULL, TRUE),
       (3, 10, NULL, FALSE),
       (3, 11, NULL, TRUE),
       (4, 1, NULL, FALSE),
       (4, 2, NULL, TRUE),
       (4, 3, NULL, FALSE),
       (4, 4, NULL, TRUE),
       (4, 5, NULL, FALSE),
       (4, 6, NULL, TRUE),
       (4, 7, NULL, FALSE),
       (4, 8, NULL, TRUE),
       (4, 9, NULL, FALSE),
       (4, 10, NULL, TRUE),
       (4, 11, NULL, FALSE),
       (5, 1, NULL, TRUE),
       (5, 2, NULL, FALSE),
       (5, 3, NULL, TRUE),
       (5, 4, NULL, FALSE),
       (5, 5, NULL, TRUE),
       (5, 6, NULL, FALSE),
       (5, 7, NULL, TRUE),
       (5, 8, NULL, FALSE),
       (5, 9, NULL, TRUE),
       (5, 10, NULL, FALSE),
       (5, 11, NULL, TRUE),
       (6, 1, NULL, FALSE),
       (6, 2, NULL, TRUE),
       (6, 3, NULL, FALSE),
       (6, 4, NULL, TRUE),
       (6, 5, NULL, FALSE),
       (6, 6, NULL, TRUE),
       (6, 7, NULL, FALSE),
       (6, 8, NULL, TRUE),
       (6, 9, NULL, FALSE),
       (6, 10, NULL, TRUE),
       (6, 11, NULL, FALSE),

       (1, NULL, 1, TRUE),
       (1, NULL, 2, FALSE),
       (1, NULL, 3, TRUE),
       (1, NULL, 4, FALSE),
       (1, NULL, 5, TRUE),
       (1, NULL, 6, FALSE),
       (1, NULL, 7, TRUE),
       (1, NULL, 8, FALSE),
       (1, NULL, 9, TRUE),
       (1, NULL, 10, FALSE),
       (1, NULL, 11, TRUE),
       (1, NULL, 12, FALSE),
       (1, NULL, 13, TRUE),
       (1, NULL, 14, FALSE),
       (1, NULL, 15, TRUE),
       (1, NULL, 16, FALSE),
       (1, NULL, 17, TRUE),
       (1, NULL, 18, FALSE),
       (1, NULL, 19, TRUE),
       (1, NULL, 20, FALSE),
       (2, NULL, 21, TRUE),
       (2, NULL, 22, FALSE),
       (2, NULL, 23, TRUE),
       (2, NULL, 24, FALSE),
       (2, NULL, 25, TRUE),
       (2, NULL, 26, FALSE),
       (2, NULL, 27, TRUE),
       (2, NULL, 28, FALSE),
       (2, NULL, 29, TRUE),
       (2, NULL, 30, FALSE),
       (3, NULL, 31, TRUE),
       (3, NULL, 32, FALSE),
       (3, NULL, 33, TRUE),
       (3, NULL, 34, FALSE),
       (3, NULL, 35, TRUE),
       (3, NULL, 36, FALSE),
       (3, NULL, 37, TRUE),
       (3, NULL, 38, FALSE),
       (3, NULL, 39, TRUE),
       (3, NULL, 40, FALSE),
       (4, NULL, 41, TRUE),
       (4, NULL, 42, FALSE),
       (4, NULL, 43, TRUE),
       (4, NULL, 44, FALSE),
       (4, NULL, 45, TRUE),
       (4, NULL, 46, FALSE),
       (4, NULL, 47, TRUE),
       (4, NULL, 48, FALSE),
       (4, NULL, 49, TRUE),
       (6, NULL, 1, FALSE),
       (6, NULL, 2, TRUE),
       (6, NULL, 3, FALSE),
       (6, NULL, 4, TRUE),
       (6, NULL, 5, FALSE),
       (6, NULL, 6, TRUE),
       (6, NULL, 7, FALSE),
       (6, NULL, 8, TRUE),
       (6, NULL, 9, FALSE),
       (6, NULL, 10, TRUE);